[package]
name = "mlb-jsonl-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
rzozowski = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.27", features = ["derive"] }
