[package]
name = "mlb-jsonl-parser"
version = "0.1.0"
edition = "2024"

[lib]
name = "mlb_jsonl_parser"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.27", features = ["derive"] }
pyo3 = { version = "0.24.2" }
